label:
  service: "${SERVICE:janus.gate.interface}"
  profile: "${PROFILE:DEV}"
  color: "${COLOR:local}"
  node: "${NODE}"
  encrypted: true
  language: "${LANGUAGE:en}"
trace:
  endpoint: http://localhost:14268/api/traces
log:
  type: zap
  level: debug
compress:
  weak: 10240 # 10KB
  strong: 1024000 # 1MB
server:
  tcp:
    addr: 0.0.0.0:7001
  ws:
    addr: 0.0.0.0:7002
    path: /ws
  kcp:
    addr: 0.0.0.0:7003
  http:
    addr: 0.0.0.0:8100
    timeout: 0.5s
  grpc:
    addr: 0.0.0.0:9100
    timeout: 0.5s
data:
  gateway_route_table_alive_duration: 600s
  app_route_table_alive_duration: 600s
  redis:
    addr: localhost:6379
    password: ${REDIS_PASSWORD}
    dial_timeout: 2s
    read_timeout: 0.5s
    write_timeout: 0.5s
