// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gate/internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         *Label                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Trace         *Trace                 `protobuf:"bytes,2,opt,name=trace,proto3" json:"trace,omitempty"`
	Server        *Server                `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Log           *Log                   `protobuf:"bytes,5,opt,name=log,proto3" json:"log,omitempty"`
	Secret        *Secret                `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	Compress      *Compress              `protobuf:"bytes,7,opt,name=compress,proto3" json:"compress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_gate_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_gate_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_gate_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetLabel() *Label {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *Bootstrap) GetTrace() *Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Bootstrap) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *Bootstrap) GetCompress() *Compress {
	if x != nil {
		return x.Compress
	}
	return nil
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Profile       string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Zone          uint32                 `protobuf:"varint,5,opt,name=zone,proto3" json:"zone,omitempty"`
	Node          string                 `protobuf:"bytes,6,opt,name=node,proto3" json:"node,omitempty"`
	Encrypted     bool                   `protobuf:"varint,7,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	Language      string                 `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_gate_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_gate_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_gate_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Label) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Label) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *Label) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Label) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Label) GetZone() uint32 {
	if x != nil {
		return x.Zone
	}
	return 0
}

func (x *Label) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Label) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

func (x *Label) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type Trace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_gate_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_gate_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_gate_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Trace) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_gate_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_gate_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_gate_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Log) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type Compress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weak          int64                  `protobuf:"varint,1,opt,name=weak,proto3" json:"weak,omitempty"`
	Strong        int64                  `protobuf:"varint,2,opt,name=strong,proto3" json:"strong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Compress) Reset() {
	*x = Compress{}
	mi := &file_gate_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compress) ProtoMessage() {}

func (x *Compress) ProtoReflect() protoreflect.Message {
	mi := &file_gate_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compress.ProtoReflect.Descriptor instead.
func (*Compress) Descriptor() ([]byte, []int) {
	return file_gate_internal_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Compress) GetWeak() int64 {
	if x != nil {
		return x.Weak
	}
	return 0
}

func (x *Compress) GetStrong() int64 {
	if x != nil {
		return x.Strong
	}
	return 0
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tcp           *Server_TCP            `protobuf:"bytes,1,opt,name=tcp,proto3" json:"tcp,omitempty"`
	Http          *Server_HTTP           `protobuf:"bytes,2,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,3,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Health        string                 `protobuf:"bytes,4,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_gate_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_gate_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_gate_internal_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Server) GetTcp() *Server_TCP {
	if x != nil {
		return x.Tcp
	}
	return nil
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redis         *Data_Redis            `protobuf:"bytes,1,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_gate_internal_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_gate_internal_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_gate_internal_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type Registry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etcd          *Etcd                  `protobuf:"bytes,1,opt,name=etcd,proto3" json:"etcd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_gate_internal_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_gate_internal_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_gate_internal_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Registry) GetEtcd() *Etcd {
	if x != nil {
		return x.Etcd
	}
	return nil
}

type Etcd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []string               `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Etcd) Reset() {
	*x = Etcd{}
	mi := &file_gate_internal_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Etcd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Etcd) ProtoMessage() {}

func (x *Etcd) ProtoReflect() protoreflect.Message {
	mi := &file_gate_internal_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Etcd.ProtoReflect.Descriptor instead.
func (*Etcd) Descriptor() ([]byte, []int) {
	return file_gate_internal_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *Etcd) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Etcd) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Etcd) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Secret struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AccountAesKey        string                 `protobuf:"bytes,1,opt,name=account_aes_key,json=accountAesKey,proto3" json:"account_aes_key,omitempty"`
	ServerCertVersion    int32                  `protobuf:"varint,2,opt,name=server_cert_version,json=serverCertVersion,proto3" json:"server_cert_version,omitempty"`
	ServerCertPrivateKey string                 `protobuf:"bytes,3,opt,name=server_cert_private_key,json=serverCertPrivateKey,proto3" json:"server_cert_private_key,omitempty"`
	ClientCertVersion    int32                  `protobuf:"varint,4,opt,name=client_cert_version,json=clientCertVersion,proto3" json:"client_cert_version,omitempty"`
	ClientCert           string                 `protobuf:"bytes,5,opt,name=client_cert,json=clientCert,proto3" json:"client_cert,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_gate_internal_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_gate_internal_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_gate_internal_conf_conf_proto_rawDescGZIP(), []int{9}
}

func (x *Secret) GetAccountAesKey() string {
	if x != nil {
		return x.AccountAesKey
	}
	return ""
}

func (x *Secret) GetServerCertVersion() int32 {
	if x != nil {
		return x.ServerCertVersion
	}
	return 0
}

func (x *Secret) GetServerCertPrivateKey() string {
	if x != nil {
		return x.ServerCertPrivateKey
	}
	return ""
}

func (x *Secret) GetClientCertVersion() int32 {
	if x != nil {
		return x.ClientCertVersion
	}
	return 0
}

func (x *Secret) GetClientCert() string {
	if x != nil {
		return x.ClientCert
	}
	return ""
}

type Server_TCP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_TCP) Reset() {
	*x = Server_TCP{}
	mi := &file_gate_internal_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_TCP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_TCP) ProtoMessage() {}

func (x *Server_TCP) ProtoReflect() protoreflect.Message {
	mi := &file_gate_internal_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_TCP.ProtoReflect.Descriptor instead.
func (*Server_TCP) Descriptor() ([]byte, []int) {
	return file_gate_internal_conf_conf_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Server_TCP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_gate_internal_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_gate_internal_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_gate_internal_conf_conf_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_gate_internal_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_gate_internal_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_gate_internal_conf_conf_proto_rawDescGZIP(), []int{5, 2}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Cluster       bool                   `protobuf:"varint,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	DialTimeout   *durationpb.Duration   `protobuf:"bytes,4,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,5,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,6,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_gate_internal_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_gate_internal_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_gate_internal_conf_conf_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetCluster() bool {
	if x != nil {
		return x.Cluster
	}
	return false
}

func (x *Data_Redis) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

var File_gate_internal_conf_conf_proto protoreflect.FileDescriptor

const file_gate_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x1dgate/internal/conf/conf.proto\x12\x12gate.internal.conf\x1a\x1egoogle/protobuf/duration.proto\"\xe8\x02\n" +
	"\tBootstrap\x12/\n" +
	"\x05label\x18\x01 \x01(\v2\x19.gate.internal.conf.LabelR\x05label\x12/\n" +
	"\x05trace\x18\x02 \x01(\v2\x19.gate.internal.conf.TraceR\x05trace\x122\n" +
	"\x06server\x18\x03 \x01(\v2\x1a.gate.internal.conf.ServerR\x06server\x12,\n" +
	"\x04data\x18\x04 \x01(\v2\x18.gate.internal.conf.DataR\x04data\x12)\n" +
	"\x03log\x18\x05 \x01(\v2\x17.gate.internal.conf.LogR\x03log\x122\n" +
	"\x06secret\x18\x06 \x01(\v2\x1a.gate.internal.conf.SecretR\x06secret\x128\n" +
	"\bcompress\x18\a \x01(\v2\x1c.gate.internal.conf.CompressR\bcompress\"\xcd\x01\n" +
	"\x05Label\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x12\n" +
	"\x04zone\x18\x05 \x01(\rR\x04zone\x12\x12\n" +
	"\x04node\x18\x06 \x01(\tR\x04node\x12\x1c\n" +
	"\tencrypted\x18\a \x01(\bR\tencrypted\x12\x1a\n" +
	"\blanguage\x18\b \x01(\tR\blanguage\"#\n" +
	"\x05Trace\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\"/\n" +
	"\x03Log\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\"6\n" +
	"\bCompress\x12\x12\n" +
	"\x04weak\x18\x01 \x01(\x03R\x04weak\x12\x16\n" +
	"\x06strong\x18\x02 \x01(\x03R\x06strong\"\xad\x03\n" +
	"\x06Server\x120\n" +
	"\x03tcp\x18\x01 \x01(\v2\x1e.gate.internal.conf.Server.TCPR\x03tcp\x123\n" +
	"\x04http\x18\x02 \x01(\v2\x1f.gate.internal.conf.Server.HTTPR\x04http\x123\n" +
	"\x04grpc\x18\x03 \x01(\v2\x1f.gate.internal.conf.Server.GRPCR\x04grpc\x12\x16\n" +
	"\x06health\x18\x04 \x01(\tR\x06health\x1a\x19\n" +
	"\x03TCP\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xcc\x02\n" +
	"\x04Data\x124\n" +
	"\x05redis\x18\x01 \x01(\v2\x1e.gate.internal.conf.Data.RedisR\x05redis\x1a\x8d\x02\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x18\n" +
	"\acluster\x18\x03 \x01(\bR\acluster\x12<\n" +
	"\fdial_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\vdialTimeout\x12<\n" +
	"\fread_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\"8\n" +
	"\bRegistry\x12,\n" +
	"\x04etcd\x18\x01 \x01(\v2\x18.gate.internal.conf.EtcdR\x04etcd\"\\\n" +
	"\x04Etcd\x12\x1c\n" +
	"\tendpoints\x18\x01 \x03(\tR\tendpoints\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\xe8\x01\n" +
	"\x06Secret\x12&\n" +
	"\x0faccount_aes_key\x18\x01 \x01(\tR\raccountAesKey\x12.\n" +
	"\x13server_cert_version\x18\x02 \x01(\x05R\x11serverCertVersion\x125\n" +
	"\x17server_cert_private_key\x18\x03 \x01(\tR\x14serverCertPrivateKey\x12.\n" +
	"\x13client_cert_version\x18\x04 \x01(\x05R\x11clientCertVersion\x12\x1f\n" +
	"\vclient_cert\x18\x05 \x01(\tR\n" +
	"clientCertB:Z8github.com/go-pantheon/janus/app/gate/internal/conf;confb\x06proto3"

var (
	file_gate_internal_conf_conf_proto_rawDescOnce sync.Once
	file_gate_internal_conf_conf_proto_rawDescData []byte
)

func file_gate_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_gate_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_gate_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gate_internal_conf_conf_proto_rawDesc), len(file_gate_internal_conf_conf_proto_rawDesc)))
	})
	return file_gate_internal_conf_conf_proto_rawDescData
}

var file_gate_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_gate_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: gate.internal.conf.Bootstrap
	(*Label)(nil),               // 1: gate.internal.conf.Label
	(*Trace)(nil),               // 2: gate.internal.conf.Trace
	(*Log)(nil),                 // 3: gate.internal.conf.Log
	(*Compress)(nil),            // 4: gate.internal.conf.Compress
	(*Server)(nil),              // 5: gate.internal.conf.Server
	(*Data)(nil),                // 6: gate.internal.conf.Data
	(*Registry)(nil),            // 7: gate.internal.conf.Registry
	(*Etcd)(nil),                // 8: gate.internal.conf.Etcd
	(*Secret)(nil),              // 9: gate.internal.conf.Secret
	(*Server_TCP)(nil),          // 10: gate.internal.conf.Server.TCP
	(*Server_HTTP)(nil),         // 11: gate.internal.conf.Server.HTTP
	(*Server_GRPC)(nil),         // 12: gate.internal.conf.Server.GRPC
	(*Data_Redis)(nil),          // 13: gate.internal.conf.Data.Redis
	(*durationpb.Duration)(nil), // 14: google.protobuf.Duration
}
var file_gate_internal_conf_conf_proto_depIdxs = []int32{
	1,  // 0: gate.internal.conf.Bootstrap.label:type_name -> gate.internal.conf.Label
	2,  // 1: gate.internal.conf.Bootstrap.trace:type_name -> gate.internal.conf.Trace
	5,  // 2: gate.internal.conf.Bootstrap.server:type_name -> gate.internal.conf.Server
	6,  // 3: gate.internal.conf.Bootstrap.data:type_name -> gate.internal.conf.Data
	3,  // 4: gate.internal.conf.Bootstrap.log:type_name -> gate.internal.conf.Log
	9,  // 5: gate.internal.conf.Bootstrap.secret:type_name -> gate.internal.conf.Secret
	4,  // 6: gate.internal.conf.Bootstrap.compress:type_name -> gate.internal.conf.Compress
	10, // 7: gate.internal.conf.Server.tcp:type_name -> gate.internal.conf.Server.TCP
	11, // 8: gate.internal.conf.Server.http:type_name -> gate.internal.conf.Server.HTTP
	12, // 9: gate.internal.conf.Server.grpc:type_name -> gate.internal.conf.Server.GRPC
	13, // 10: gate.internal.conf.Data.redis:type_name -> gate.internal.conf.Data.Redis
	8,  // 11: gate.internal.conf.Registry.etcd:type_name -> gate.internal.conf.Etcd
	14, // 12: gate.internal.conf.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	14, // 13: gate.internal.conf.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	14, // 14: gate.internal.conf.Data.Redis.dial_timeout:type_name -> google.protobuf.Duration
	14, // 15: gate.internal.conf.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	14, // 16: gate.internal.conf.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_gate_internal_conf_conf_proto_init() }
func file_gate_internal_conf_conf_proto_init() {
	if File_gate_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gate_internal_conf_conf_proto_rawDesc), len(file_gate_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gate_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_gate_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_gate_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_gate_internal_conf_conf_proto = out.File
	file_gate_internal_conf_conf_proto_goTypes = nil
	file_gate_internal_conf_conf_proto_depIdxs = nil
}
